import ffmpeg from "fluent-ffmpeg";
import ytdl from "ytdl-core";
import fs from "fs";
import path from "path";
import { nanoid } from "nanoid";
import ffmpegInstaller from "@ffmpeg-installer/ffmpeg";
import https from "https";
import http from "http";
import { Worker } from "worker_threads";
import pLimit from "p-limit";

ffmpeg.setFfmpegPath(ffmpegInstaller.path);

// Parallel processing configuration - OPTIMIZED for maximum speed
const MAX_CONCURRENT_CLIPS = 12; // Process up to 12 clips at once (3x baseline)
const MAX_CONCURRENT_GRADING = 10; // Process up to 10 videos for color grading at once (3x baseline)
const FRAME_EXTRACTION_CONCURRENCY = 16; // Extract 16 frames in parallel (3x baseline)

// CRITICAL FIX: Use persistent storage for ALL videos to prevent data loss
// /tmp gets wiped periodically - we must use uploads/ for persistence
const PROCESSING_ROOT = path.join(process.cwd(), "uploads");
const VIDEOS_DIR = path.join(PROCESSING_ROOT, "videos");
const THUMBNAILS_DIR = path.join(PROCESSING_ROOT, "thumbnails");
const LUTS_DIR = path.join(process.cwd(), "server", "luts");

// Also keep original uploads dir for source videos
const SOURCE_UPLOADS_DIR = path.join(process.cwd(), "uploads", "videos");

// Ensure directories exist
if (!fs.existsSync(VIDEOS_DIR)) {
  fs.mkdirSync(VIDEOS_DIR, { recursive: true });
}
if (!fs.existsSync(THUMBNAILS_DIR)) {
  fs.mkdirSync(THUMBNAILS_DIR, { recursive: true });
}
if (!fs.existsSync(LUTS_DIR)) {
  fs.mkdirSync(LUTS_DIR, { recursive: true });
}
if (!fs.existsSync(SOURCE_UPLOADS_DIR)) {
  fs.mkdirSync(SOURCE_UPLOADS_DIR, { recursive: true });
}

console.log(`[VideoProcessor] ✓ Using persistent storage: ${PROCESSING_ROOT}`);
console.log(`[VideoProcessor] Videos directory: ${VIDEOS_DIR}`);

// Metadata cache to avoid repeated ffprobe calls (PERFORMANCE OPTIMIZATION)
// Cache key includes file size + mtime to invalidate on file changes
const metadataCache = new Map<string, { duration: number; width: number; height: number; metadata: any }>();

export class VideoProcessor {
  // Lock to prevent concurrent LUT generation
  private static lutGenerationLock: Promise<void> | null = null;

  // Initialize LUT files on first use using proper 3D LUT generator
  private static async ensureLUTFiles(): Promise<void> {
    // If generation is already in progress, wait for it
    if (this.lutGenerationLock) {
      console.log('[VideoProcessor] Waiting for ongoing LUT generation...');
      await this.lutGenerationLock;
      return;
    }

    const { generateAllLUTs, getLUTPresets } = await import('./lut-generator');

    // CRITICAL SECTION: Re-check lock after import (prevents race condition)
    if (this.lutGenerationLock) {
      console.log('[VideoProcessor] Lock acquired by concurrent request during import, waiting...');
      await this.lutGenerationLock;
      return;
    }

    // Get canonical list of LUT presets from generator
    const allLUTPresets = getLUTPresets();

    // Check if ALL LUT files exist
    const allExist = allLUTPresets.every(name =>
      fs.existsSync(path.join(LUTS_DIR, `${name}.cube`))
    );

    if (!allExist) {
      // Atomically acquire lock (if still null)
      if (this.lutGenerationLock) {
        console.log('[VideoProcessor] Lock acquired between checks, waiting...');
        await this.lutGenerationLock;
        return;
      }

      // Set lock and begin generation
      this.lutGenerationLock = (async () => {
        try {
          // Double-check pattern: verify files still missing inside lock
          const stillMissingBeforeGen = allLUTPresets.filter(name =>
            !fs.existsSync(path.join(LUTS_DIR, `${name}.cube`))
          );

          if (stillMissingBeforeGen.length === 0) {
            // Another request completed generation while we waited
            console.log('[VideoProcessor] LUTs already generated by concurrent request');
            return;
          }

          console.log(`[VideoProcessor] Generating ${stillMissingBeforeGen.length} missing 3D LUTs...`);

          generateAllLUTs(); // Synchronous blocking call - generates all LUTs before returning

          // Revalidate that all files were created successfully
          const stillMissing = allLUTPresets.filter(name =>
            !fs.existsSync(path.join(LUTS_DIR, `${name}.cube`))
          );

          if (stillMissing.length > 0) {
            throw new Error(`LUT generation incomplete: missing ${stillMissing.join(', ')}`);
          }

          console.log(`[VideoProcessor] LUT generation complete - all ${allLUTPresets.length} presets ready`);
        } catch (error) {
          console.error('[VideoProcessor] LUT generation failed:', error);
          throw new Error(`Failed to generate LUT files: ${error instanceof Error ? error.message : String(error)}`);
        } finally {
          // Always release lock, even on early return
          this.lutGenerationLock = null;
        }
      })();

      await this.lutGenerationLock;
    }
  }

  // Get video metadata with caching (cache invalidates if file changes)
  static async getVideoMetadata(videoPath: string): Promise<{ duration: number; width: number; height: number; metadata: any }> {
    // Create cache key with file stats to detect changes
    const stats = fs.statSync(videoPath);
    const cacheKey = `${videoPath}:${stats.size}:${stats.mtimeMs}`;

    if (metadataCache.has(cacheKey)) {
      console.log(`[VideoProcessor] Using cached metadata for ${path.basename(videoPath)}`);
      return metadataCache.get(cacheKey)!;
    }

    return new Promise((resolve, reject) => {
      ffmpeg.ffprobe(videoPath, (err: any, metadata: any) => {
        if (err) {
          reject(err);
          return;
        }
        const duration = metadata.format.duration || 0;
        const videoStream = metadata.streams.find((s: any) => s.codec_type === 'video');
        const width = videoStream?.width || 1920;
        const height = videoStream?.height || 1080;

        const cachedData = { duration: Math.floor(duration), width, height, metadata };
        metadataCache.set(cacheKey, cachedData);
        console.log(`[VideoProcessor] Cached metadata for ${path.basename(videoPath)}: ${duration}s, ${width}x${height}`);
        resolve(cachedData);
      });
    });
  }
  static async downloadFromUrl(url: string): Promise<{
    videoPath: string;
    duration: number;
  }> {
    const videoId = nanoid();
    const videoPath = path.join(VIDEOS_DIR, `${videoId}.mp4`);

    // Check if it's a YouTube URL
    if (url.includes("youtube.com") || url.includes("youtu.be")) {
      return this.downloadYouTubeVideo(url);
    }

    // For other URLs (Google Drive, Dropbox, direct URLs), use generic download
    return this.downloadGenericUrl(url, videoPath);
  }

  private static async downloadYouTubeVideo(url: string): Promise<{
    videoPath: string;
    duration: number;
  }> {
    const videoId = nanoid();
    const videoPath = path.join(VIDEOS_DIR, `${videoId}.mp4`);

    return new Promise((resolve, reject) => {
      const stream = ytdl(url, {
        quality: "highest",
        filter: "audioandvideo",
      });

      stream.pipe(fs.createWriteStream(videoPath));

      stream.on("end", async () => {
        try {
          // Use cached metadata method
          const { duration } = await this.getVideoMetadata(videoPath);
          resolve({ videoPath, duration });
        } catch (err) {
          reject(err);
        }
      });

      stream.on("error", reject);
    });
  }

  private static async downloadGenericUrl(
    url: string,
    videoPath: string
  ): Promise<{
    videoPath: string;
    duration: number;
  }> {
    // For Google Drive shareable links, convert to direct download
    let downloadUrl = url;
    if (url.includes("drive.google.com")) {
      const fileId = url.match(/\/d\/([^/]+)/)?.[1] || url.match(/id=([^&]+)/)?.[1];
      if (fileId) {
        downloadUrl = `https://drive.google.com/uc?export=download&id=${fileId}`;
      }
    }

    return new Promise((resolve, reject) => {
      const protocol = downloadUrl.startsWith("https") ? https : http;

      protocol.get(downloadUrl, (response: any) => {
        if (response.statusCode === 302 || response.statusCode === 301) {
          // Follow redirect
          return this.downloadGenericUrl(response.headers.location, videoPath)
            .then(resolve)
            .catch(reject);
        }

        const file = fs.createWriteStream(videoPath);
        response.pipe(file);

        file.on("finish", async () => {
          file.close();
          try {
            // Use cached metadata method
            const { duration } = await this.getVideoMetadata(videoPath);
            resolve({ videoPath, duration });
          } catch (err) {
            reject(err);
          }
        });
      }).on("error", (err: any) => {
        fs.unlink(videoPath, () => {}); // Delete the file if error
        reject(err);
      });
    });
  }

  static async extractThumbnail(
    videoPath: string,
    timestamp: number
  ): Promise<string> {
    const thumbnailId = nanoid();
    const thumbnailPath = path.join(THUMBNAILS_DIR, `${thumbnailId}.jpg`);

    return new Promise((resolve, reject) => {
      ffmpeg(videoPath)
        .screenshots({
          timestamps: [timestamp],
          filename: `${thumbnailId}.jpg`,
          folder: THUMBNAILS_DIR,
          size: "320x180",
        })
        .on("end", () => resolve(`/processing/thumbnails/${thumbnailId}.jpg`))
        .on("error", reject);
    });
  }

  static async extractClip(
    videoPath: string,
    startTime: number,
    endTime: number,
    options?: { reEncode?: boolean; ultraFast?: boolean }
  ): Promise<string> {
    const clipId = nanoid();
    const clipPath = path.join(VIDEOS_DIR, `clip-${clipId}.mp4`);

    console.log(`[extractClip] Extracting ${startTime}s-${endTime}s from ${path.basename(videoPath)} (reEncode: ${options?.reEncode ?? false}, ultraFast: ${options?.ultraFast ?? false})`);

    return new Promise((resolve, reject) => {
      const command = ffmpeg(videoPath)
        .setStartTime(startTime)
        .setDuration(endTime - startTime)
        .output(clipPath);

      if (options?.reEncode) {
        // Ultra-fast mode for speed (10x faster)
        if (options.ultraFast) {
          command.outputOptions([
            '-c:v', 'libx264',
            '-preset', 'veryfast', // Faster than ultrafast for better quality/speed ratio
            '-tune', 'zerolatency', // Optimize for speed
            '-threads', '0', // Use all CPU cores
            '-crf', '28', // Higher CRF for faster encoding (still good quality)
            '-c:a', 'copy', // Don't re-encode audio
            '-movflags', '+faststart',
            '-avoid_negative_ts', 'make_zero',
            '-fps_mode', 'passthrough' // Don't modify framerate
          ]);
        } else {
          command.outputOptions([
            '-c:v', 'libx264',
            '-preset', 'ultrafast',
            '-threads', '0',
            '-crf', '23',
            '-c:a', 'aac',
            '-b:a', '128k',
            '-movflags', '+faststart',
            '-avoid_negative_ts', 'make_zero'
          ]);
        }
      } else {
        command.outputOptions([
          '-c:v', 'copy',
          '-c:a', 'copy',
          '-movflags', '+faststart',
          '-avoid_negative_ts', 'make_zero'
        ]);
      }

      command
        .on("end", async () => {
          const stats = fs.statSync(clipPath);
          console.log(`[extractClip] Successfully extracted clip: ${clipId} (${(stats.size / 1024).toFixed(1)}KB)`);

          if (stats.size < 1000) {
            console.warn(`[extractClip] Warning: Clip ${clipId} is very small, may be corrupted`);
          }
          resolve(clipPath);
        })
        .on("error", (err) => {
          console.error(`[extractClip] Error extracting clip:`, err.message);
          reject(err);
        })
        .on("stderr", (stderrLine) => {
          console.log(`[extractClip] FFmpeg: ${stderrLine}`);
        })
        .run();
    });
  }

  // PARALLEL PROCESSING: Extract multiple clips concurrently
  static async extractClipsParallel(
    videoPath: string,
    clipSpecs: Array<{ startTime: number; endTime: number; id?: string }>,
    options?: { reEncode?: boolean },
    onProgress?: (completed: number, total: number) => void // Added onProgress callback
  ): Promise<string[]> {
    console.log(`[extractClipsParallel] Extracting ${clipSpecs.length} clips in parallel (max ${MAX_CONCURRENT_CLIPS} concurrent)`);
    const startTime = Date.now();

    const limit = pLimit(MAX_CONCURRENT_CLIPS);

    let completed = 0;
    const total = clipSpecs.length;

    const extractionPromises = clipSpecs.map((spec, index) =>
      limit(async () => {
        try {
          const clipPath = await this.extractClip(
            videoPath,
            spec.startTime,
            spec.endTime,
            options
          );
          completed++;
          if (onProgress) onProgress(completed, total); // Call progress callback
          console.log(`[extractClipsParallel] Completed clip ${index + 1}/${clipSpecs.length}`);
          return clipPath;
        } catch (error: any) {
          console.error(`[extractClipsParallel] Error extracting clip ${index + 1}:`, error.message);
          // Decide how to handle errors: re-throw, return null, or continue
          throw error; // Re-throwing to stop Promise.all if any clip fails
        }
      })
    );

    const clipPaths = await Promise.all(extractionPromises);
    const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
    console.log(`[extractClipsParallel] ✓ Extracted ${clipPaths.length} clips in ${elapsed}s (${(clipSpecs.length / parseFloat(elapsed)).toFixed(1)} clips/s)`);

    return clipPaths;
  }

  static async concatenateClips(
    clipPaths: string[],
    outputPath: string
  ): Promise<void> {
    const concatListPath = path.join(VIDEOS_DIR, `concat-${nanoid()}.txt`);

    console.log(`[concatenateClips] Concatenating ${clipPaths.length} clips`);

    // Verify all clips exist
    for (const clipPath of clipPaths) {
      if (!fs.existsSync(clipPath)) {
        throw new Error(`Clip not found: ${clipPath}`);
      }
    }

    // Create concat list file with absolute paths
    const concatList = clipPaths.map(p => `file '${path.resolve(p)}'`).join('\n');
    fs.writeFileSync(concatListPath, concatList);
    console.log(`[concatenateClips] Created concat list: ${concatListPath}`);

    return new Promise((resolve, reject) => {
      ffmpeg()
        .input(concatListPath)
        .inputOptions(['-f', 'concat', '-safe', '0'])
        .outputOptions([
          '-c', 'copy',
          '-movflags', '+faststart' // Optimize for web playback
        ])
        .output(outputPath)
        .on("end", () => {
          console.log(`[concatenateClips] Successfully created: ${path.basename(outputPath)}`);
          try {
            fs.unlinkSync(concatListPath);
          } catch (err) {
            console.warn(`[concatenateClips] Failed to cleanup concat list`);
          }
          resolve();
        })
        .on("error", (err) => {
          console.error(`[concatenateClips] Error:`, err.message);
          try {
            fs.unlinkSync(concatListPath);
          } catch (cleanupErr) {
            // Ignore cleanup errors
          }
          reject(err);
        })
        .on("stderr", (stderrLine) => {
          console.log(`[concatenateClips] FFmpeg: ${stderrLine}`);
        })
        .run();
    });
  }

  // Extract full audio track for OpenAI Whisper transcription
  static async extractAudioForTranscription(videoPath: string): Promise<string> {
    const audioId = nanoid();
    const audioPath = path.join(VIDEOS_DIR, `transcribe-${audioId}.mp3`);

    console.log(`[extractAudioForTranscription] Extracting audio from: ${path.basename(videoPath)}`);

    return new Promise((resolve, reject) => {
      ffmpeg(videoPath)
        .output(audioPath)
        .noVideo()
        .audioCodec("libmp3lame")
        .audioFrequency(16000) // 16kHz recommended for Whisper
        .audioChannels(1) // Mono
        .audioBitrate("64k") // Low bitrate sufficient for speech
        .on("end", () => {
          console.log(`[extractAudioForTranscription] Audio extracted: ${path.basename(audioPath)}`);
          resolve(audioPath);
        })
        .on("error", (err) => {
          console.error(`[extractAudioForTranscription] Error:`, err.message);
          reject(err);
        })
        .run();
    });
  }

  // AUTO-TRIM FILLER WORDS - Remove "um", "uh", "like", "you know"
  static detectFillerWords(segments: Array<{ start: number; end: number; text: string }>): Array<{ start: number; end: number }> {
    const fillerWords = ['um', 'uh', 'like', 'you know', 'i mean', 'basically', 'actually', 'literally'];
    const fillerSegments: Array<{ start: number; end: number }> = [];

    for (const segment of segments) {
      const words = segment.text.toLowerCase().split(/\s+/);
      const segmentDuration = segment.end - segment.start;
      const timePerWord = segmentDuration / words.length;

      words.forEach((word, index) => {
        const cleanWord = word.replace(/[.,!?]/g, '');
        if (fillerWords.includes(cleanWord)) {
          const wordStart = segment.start + (index * timePerWord);
          const wordEnd = wordStart + timePerWord;
          fillerSegments.push({ start: wordStart, end: wordEnd });
          console.log(`[AutoTrim] Detected filler word "${cleanWord}" at ${wordStart.toFixed(2)}s - ${wordEnd.toFixed(2)}s`);
        }
      });
    }

    return fillerSegments;
  }

  // Remove filler word segments from video
  static async removeFillerWords(
    videoPath: string,
    fillerSegments: Array<{ start: number; end: number }>
  ): Promise<string> {
    if (fillerSegments.length === 0) {
      console.log(`[AutoTrim] No filler words detected, returning original video`);
      return videoPath;
    }

    const outputId = nanoid();
    const outputPath = path.join(VIDEOS_DIR, `autotrim-${outputId}.mp4`);

    // Get video duration
    const { duration } = await this.getVideoMetadata(videoPath);

    // Create segments to KEEP (inverse of filler segments)
    const keepSegments: Array<{ start: number; end: number }> = [];
    let currentStart = 0;

    // Sort filler segments by start time
    const sortedFillers = fillerSegments.sort((a, b) => a.start - b.start);

    for (const filler of sortedFillers) {
      if (currentStart < filler.start) {
        keepSegments.push({ start: currentStart, end: filler.start });
      }
      currentStart = filler.end;
    }

    // Add final segment if there's content after last filler
    if (currentStart < duration) {
      keepSegments.push({ start: currentStart, end: duration });
    }

    console.log(`[AutoTrim] Removing ${fillerSegments.length} filler segments, keeping ${keepSegments.length} segments`);

    // Extract and concatenate keep segments
    const tempClips: string[] = [];
    for (let i = 0; i < keepSegments.length; i++) {
      const segment = keepSegments[i];
      const clipPath = await this.extractClip(videoPath, segment.start, segment.end);
      tempClips.push(clipPath);
    }

    // Concatenate all kept segments
    await this.concatenateClips(tempClips, outputPath);

    // Cleanup temp clips
    for (const clip of tempClips) {
      try {
        fs.unlinkSync(clip);
      } catch (err) {
        console.warn(`[AutoTrim] Failed to delete temp clip: ${clip}`);
      }
    }

    console.log(`[AutoTrim] Successfully removed filler words: ${path.basename(outputPath)}`);
    return outputPath;
  }

  static async cropToAspectRatio(
    videoPath: string,
    aspectRatio: "9:16" | "1:1" | "16:9"
  ): Promise<string> {
    const outputId = nanoid();
    const outputPath = path.join(VIDEOS_DIR, `cropped-${outputId}.mp4`);

    // Calculate crop filter based on aspect ratio
    const cropFilters: Record<string, string> = {
      "9:16": "crop=ih*9/16:ih", // Vertical: crop width to 9/16 of height
      "1:1": "crop=min(iw\\,ih):min(iw\\,ih)", // Square: crop to smallest dimension
      "16:9": "crop=iw:iw*9/16", // Landscape: crop height to 9/16 of width
    };

    const scaleFilters: Record<string, string> = {
      "9:16": "scale=1080:1920", // Standard vertical resolution
      "1:1": "scale=1080:1080", // Standard square resolution
      "16:9": "scale=1920:1080", // Standard landscape resolution
    };

    const filter = `${cropFilters[aspectRatio]},${scaleFilters[aspectRatio]}`;

    return new Promise((resolve, reject) => {
      ffmpeg(videoPath)
        .videoFilters(filter)
        .output(outputPath)
        .videoCodec("libx264")
        .audioCodec("aac")
        .outputOptions([
          '-preset', 'ultrafast',
          '-threads', '0',  // PERFORMANCE: Fast encoding without quality loss
          '-crf', '20'  // Constant Rate Factor: 20 for high quality
        ])
        .on("end", () => resolve(outputPath))
        .on("error", reject)
        .run();
    });
  }

  // Apply Ken Burns motion effect (slow zoom + pan)
  static async applyKenBurnsEffect(
    videoPath: string,
    intensity: "subtle" | "moderate" | "dramatic" = "moderate"
  ): Promise<string> {
    const outputId = nanoid();
    const outputPath = path.join(VIDEOS_DIR, `kenburns-${outputId}.mp4`);

    console.log(`[KenBurns] Applying ${intensity} effect to video`);

    // Get video metadata for scale calculations
    const { duration, width, height } = await this.getVideoMetadata(videoPath);

    // Ken Burns intensity presets
    const presets = {
      subtle: { startZoom: 1.0, endZoom: 1.05, panX: 0, panY: 10 }, // 5% zoom, slight down pan
      moderate: { startZoom: 1.0, endZoom: 1.1, panX: 20, panY: 20 }, // 10% zoom, diagonal pan
      dramatic: { startZoom: 1.0, endZoom: 1.2, panX: 40, panY: 30 }, // 20% zoom, strong pan
    };

    const preset = presets[intensity];
    const framerate = 60; // Assume 60fps for smooth motion

    // Calculate zoom/pan trajectory
    // zoompan filter: zoom factor increases over time, with X/Y pan
    const zoomFilter = `zoompan=z='min(zoom+0.0015,${preset.endZoom})':x='iw/2-(iw/zoom/2)+${preset.panX}*sin(on/${framerate})':y='ih/2-(ih/zoom/2)+${preset.panY}*cos(on/${framerate})':d=${duration * framerate}:s=${width}x${height}:fps=${framerate}`;

    return new Promise((resolve, reject) => {
      ffmpeg(videoPath)
        .videoFilters(zoomFilter)
        .output(outputPath)
        .videoCodec("libx264")
        .audioCodec("copy")
        .outputOptions([
          '-preset', 'ultrafast',
          '-threads', '0',
          '-crf', '20',
        ])
        .on("end", () => {
          console.log(`[KenBurns] Effect applied: ${outputPath}`);
          resolve(outputPath);
        })
        .on("error", (err) => {
          console.error(`[KenBurns] Error:`, err.message);
          reject(err);
        })
        .run();
    });
  }

  // Apply audio fade-in/fade-out for smooth audio transitions
  static async applyAudioFades(
    videoPath: string,
    fadeInDuration: number = 0.5,
    fadeOutDuration: number = 0.5
  ): Promise<string> {
    const outputId = nanoid();
    const outputPath = path.join(VIDEOS_DIR, `audiofade-${outputId}.mp4`);

    console.log(`[AudioFade] Applying fade-in: ${fadeInDuration}s, fade-out: ${fadeOutDuration}s`);

    const { duration } = await this.getVideoMetadata(videoPath);
    const fadeOutStart = Math.max(0, duration - fadeOutDuration);

    return new Promise((resolve, reject) => {
      ffmpeg(videoPath)
        .audioFilters([
          `afade=t=in:st=0:d=${fadeInDuration}`,
          `afade=t=out:st=${fadeOutStart}:d=${fadeOutDuration}`,
        ])
        .output(outputPath)
        .videoCodec("copy") // No video re-encoding
        .audioCodec("aac")
        .outputOptions(['-b:a', '192k'])
        .on("end", () => {
          console.log(`[AudioFade] Fades applied: ${outputPath}`);
          resolve(outputPath);
        })
        .on("error", (err) => {
          console.error(`[AudioFade] Error:`, err.message);
          reject(err);
        })
        .run();
    });
  }

  // Apply audio normalization (auto-level adjustment) - Updated to -14 LUFS for social media
  static async normalizeAudio(videoPath: string): Promise<string> {
    const outputId = nanoid();
    const outputPath = path.join(VIDEOS_DIR, `normalized-${outputId}.mp4`);

    console.log(`[AudioNormalize] Normalizing audio levels to -14 LUFS`);

    return new Promise((resolve, reject) => {
      ffmpeg(videoPath)
        .audioFilters([
          'loudnorm=I=-14:TP=-1.5:LRA=11', // EBU R128 loudness normalization (-14 LUFS for social media)
        ])
        .output(outputPath)
        .videoCodec("copy")
        .audioCodec("aac")
        .outputOptions(['-b:a', '192k'])
        .on("end", () => {
          console.log(`[AudioNormalize] Audio normalized to -14 LUFS: ${outputPath}`);
          resolve(outputPath);
        })
        .on("error", (err) => {
          console.error(`[AudioNormalize] Error:`, err.message);
          reject(err);
        })
        .run();
    });
  }

  // Apply noise gate (remove background noise below threshold)
  static async applyNoiseGate(
    videoPath: string,
    threshold: number = -50, // dB threshold
    gateType: "highpass" | "lowpass" | "both" = "both"
  ): Promise<string> {
    const outputId = nanoid();
    const outputPath = path.join(VIDEOS_DIR, `noisegate-${outputId}.mp4`);

    console.log(`[NoiseGate] Applying noise gate with ${gateType} filter`);

    const filters: string[] = [];

    // Highpass filter (remove low-frequency rumble below 80Hz)
    if (gateType === "highpass" || gateType === "both") {
      filters.push('highpass=f=80');
    }

    // Lowpass filter (remove high-frequency hiss above 15kHz)
    if (gateType === "lowpass" || gateType === "both") {
      filters.push('lowpass=f=15000');
    }

    // Gate filter (silence audio below threshold)
    filters.push(`agate=threshold=${threshold}dB:ratio=2:attack=20:release=250`);

    return new Promise((resolve, reject) => {
      ffmpeg(videoPath)
        .audioFilters(filters)
        .output(outputPath)
        .videoCodec("copy")
        .audioCodec("aac")
        .outputOptions(['-b:a', '192k'])
        .on("end", () => {
          console.log(`[NoiseGate] Noise gate applied: ${outputPath}`);
          resolve(outputPath);
        })
        .on("error", (err) => {
          console.error(`[NoiseGate] Error:`, err.message);
          reject(err);
        })
        .run();
    });
  }

  // Apply speech EQ (boost 2-4kHz for vocal clarity)
  static async applySpeechEQ(videoPath: string): Promise<string> {
    const outputId = nanoid();
    const outputPath = path.join(VIDEOS_DIR, `speecheq-${outputId}.mp4`);

    console.log(`[SpeechEQ] Applying speech frequency optimization (2-4kHz boost)`);

    return new Promise((resolve, reject) => {
      ffmpeg(videoPath)
        .audioFilters([
          // Parametric EQ: boost 2-4kHz (speech clarity range)
          'equalizer=f=2500:width_type=h:width=1000:g=3', // +3dB boost at 2.5kHz, 1kHz bandwidth
          // Slight cut at 200Hz (reduce muddiness)
          'equalizer=f=200:width_type=h:width=100:g=-2',
        ])
        .output(outputPath)
        .videoCodec("copy")
        .audioCodec("aac")
        .outputOptions(['-b:a', '192k'])
        .on("end", () => {
          console.log(`[SpeechEQ] Speech EQ applied: ${outputPath}`);
          resolve(outputPath);
        })
        .on("error", (err) => {
          console.error(`[SpeechEQ] Error:`, err.message);
          reject(err);
        })
        .run();
    });
  }

  // Apply de-esser (reduce sibilance in 5-8kHz range)
  static async applyDeEsser(
    videoPath: string,
    frequency: number = 6500, // Target frequency in Hz
    reduction: number = -6 // dB reduction
  ): Promise<string> {
    const outputId = nanoid();
    const outputPath = path.join(VIDEOS_DIR, `deesser-${outputId}.mp4`);

    console.log(`[DeEsser] Reducing sibilance at ${frequency}Hz`);

    return new Promise((resolve, reject) => {
      ffmpeg(videoPath)
        .audioFilters([
          // Dynamic EQ to reduce harsh "s" sounds
          `equalizer=f=${frequency}:width_type=h:width=1500:g=${reduction}`,
          // Compressor targeting high frequencies only
          'highpass=f=5000,acompressor=threshold=-20dB:ratio=3:attack=5:release=50,highpass=f=0', // Reset highpass
        ])
        .output(outputPath)
        .videoCodec("copy")
        .audioCodec("aac")
        .outputOptions(['-b:a', '192k'])
        .on("end", () => {
          console.log(`[DeEsser] De-esser applied: ${outputPath}`);
          resolve(outputPath);
        })
        .on("error", (err) => {
          console.error(`[DeEsser] Error:`, err.message);
          reject(err);
        })
        .run();
    });
  }

  // Apply compression (dynamic range control)
  static async applyCompression(
    videoPath: string,
    threshold: number = -18, // dB
    ratio: number = 3, // 3:1 compression ratio
    attack: number = 5, // milliseconds
    release: number = 50 // milliseconds
  ): Promise<string> {
    const outputId = nanoid();
    const outputPath = path.join(VIDEOS_DIR, `compressed-${outputId}.mp4`);

    console.log(`[Compression] Applying dynamic range compression (${ratio}:1 ratio)`);

    return new Promise((resolve, reject) => {
      ffmpeg(videoPath)
        .audioFilters([
          `acompressor=threshold=${threshold}dB:ratio=${ratio}:attack=${attack}:release=${release}:makeup=2`, // +2dB makeup gain
        ])
        .output(outputPath)
        .videoCodec("copy")
        .audioCodec("aac")
        .outputOptions(['-b:a', '192k'])
        .on("end", () => {
          console.log(`[Compression] Compression applied: ${outputPath}`);
          resolve(outputPath);
        })
        .on("error", (err) => {
          console.error(`[Compression] Error:`, err.message);
          reject(err);
        })
        .run();
    });
  }

  // Apply limiter (prevent clipping with -1.5 TP ceiling)
  static async applyLimiter(videoPath: string): Promise<string> {
    const outputId = nanoid();
    const outputPath = path.join(VIDEOS_DIR, `limited-${outputId}.mp4`);

    console.log(`[Limiter] Applying limiter with -1.5 TP ceiling`);

    return new Promise((resolve, reject) => {
      ffmpeg(videoPath)
        .audioFilters([
          'alimiter=limit=-1.5dB:attack=5:release=50', // Prevent peaks above -1.5dB
        ])
        .output(outputPath)
        .videoCodec("copy")
        .audioCodec("aac")
        .outputOptions(['-b:a', '192k'])
        .on("end", () => {
          console.log(`[Limiter] Limiter applied: ${outputPath}`);
          resolve(outputPath);
        })
        .on("error", (err) => {
          console.error(`[Limiter] Error:`, err.message);
          reject(err);
        })
        .run();
    });
  }

  // Master audio chain (all audio finishing steps in optimal order)
  static async applyMasterAudioChain(
    videoPath: string,
    options: {
      noiseGate?: boolean;
      speechEQ?: boolean;
      deEsser?: boolean;
      compression?: boolean;
      limiter?: boolean;
      normalization?: boolean;
    } = {}
  ): Promise<string> {
    const {
      noiseGate = true,
      speechEQ = true,
      deEsser = true,
      compression = true,
      limiter = true,
      normalization = true,
    } = options;

    console.log(`[MasterAudio] Starting master audio chain processing...`);
    let currentPath = videoPath;

    try {
      // Step 1: Noise gate (remove background noise first)
      if (noiseGate) {
        currentPath = await this.applyNoiseGate(currentPath);
      }

      // Step 2: Speech EQ (enhance vocal clarity)
      if (speechEQ) {
        currentPath = await this.applySpeechEQ(currentPath);
      }

      // Step 3: De-esser (reduce harsh sibilance)
      if (deEsser) {
        currentPath = await this.applyDeEsser(currentPath);
      }

      // Step 4: Compression (even out dynamics)
      if (compression) {
        currentPath = await this.applyCompression(currentPath);
      }

      // Step 5: Limiter (prevent clipping)
      if (limiter) {
        currentPath = await this.applyLimiter(currentPath);
      }

      // Step 6: Normalization to -14 LUFS (final loudness)
      if (normalization) {
        currentPath = await this.normalizeAudio(currentPath);
      }

      console.log(`[MasterAudio] ✓ Master audio chain complete: ${currentPath}`);
      return currentPath;
    } catch (error: any) {
      console.error(`[MasterAudio] Error in audio chain:`, error.message);
      throw error;
    }
  }

  // PARALLEL PROCESSING: Apply color grading to multiple videos concurrently
  static async applyColorGradingBatch(
    videoPaths: string[],
    mood: string,
    onProgress?: (completed: number, total: number) => void // Added onProgress callback
  ): Promise<string[]> {
    console.log(`[applyColorGradingBatch] Applying ${mood} to ${videoPaths.length} videos in parallel`);
    const startTime = Date.now();

    const limit = pLimit(MAX_CONCURRENT_GRADING);

    let completed = 0;
    const total = videoPaths.length;

    const gradingPromises = videoPaths.map((videoPath, index) =>
      limit(async () => {
        try {
          const gradedPath = await this.applyColorGrading(videoPath, mood);
          completed++;
          if (onProgress) onProgress(completed, total); // Call progress callback
          console.log(`[applyColorGradingBatch] Completed ${index + 1}/${videoPaths.length}`);
          return gradedPath;
        } catch (error: any) {
          console.error(`[applyColorGradingBatch] Error grading video ${index + 1}:`, error.message);
          throw error;
        }
      })
    );

    const gradedPaths = await Promise.all(gradingPromises);
    const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
    console.log(`[applyColorGradingBatch] ✓ Graded ${gradedPaths.length} videos in ${elapsed}s`);

    return gradedPaths;
  }

  static async applyColorGrading(
    videoPath: string,
    mood: string,
    fastMode: boolean = false
  ): Promise<string> {
    const outputId = nanoid();
    const outputPath = path.join(VIDEOS_DIR, `graded-${outputId}.mp4`);

    console.log(`[applyColorGrading] Applying ${mood} preset using LUT-based method (fastMode: ${fastMode})`);
    const startTime = Date.now();

    // Ensure LUT files exist
    await this.ensureLUTFiles();

    // ALL 14 LUT-based presets (10x faster than filter chains)
    const lutPresets = [
      "instagram", "tiktok", "youtube",           // Social Media (3)
      "vibrant", "corporate", "cinematic",        // Basic (3)
      "dramatic", "pastel", "neon",               // Mood-Based (3)
      "vintage", "noir", "golden", "sunset", "highcontrast"  // Film Emulations (5)
    ];

    // Check if this preset has a LUT
    const lutPath = path.join(LUTS_DIR, `${mood}.cube`);
    const useLUT = lutPresets.includes(mood) && fs.existsSync(lutPath);

    if (useLUT) {
      // FAST PATH: Use LUT for instant color grading (~3-5s)
      console.log(`[applyColorGrading] Using LUT file: ${lutPath}`);

      return new Promise((resolve, reject) => {
        ffmpeg(videoPath)
          .videoFilters(`lut3d='${lutPath}'`)
          .output(outputPath)
          .videoCodec("libx264")
          .audioCodec("copy")
          .outputOptions(fastMode ? [
            '-preset', 'veryfast',  // 2x faster than ultrafast
            '-crf', '26',  // Higher CRF for speed
            '-threads', '0'
          ] : [
            '-preset', 'ultrafast',  // Fastest encoding for LUT application
            '-crf', '20'
          ])
          .on("end", () => {
            const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
            console.log(`[applyColorGrading] LUT applied in ${elapsed}s (10x faster!)`);
            resolve(outputPath);
          })
          .on("error", (err) => {
            console.error(`[applyColorGrading] LUT error:`, err.message);
            reject(err);
          })
          .run();
      });
    }

    // SLOW PATH: Fallback to filter chains for other presets
    console.log(`[applyColorGrading] Using filter chain for ${mood} (slower)`);

    // 14 COLOR GRADING PRESETS - Social Media Optimized & Film Emulations
    const filters: Record<string, string> = {
      // ORIGINAL BASIC PRESETS (3)
      vibrant: "eq=contrast=1.2:brightness=0.05:saturation=1.5,hue=s=1.2",
      corporate: "eq=contrast=1.1:brightness=0:saturation=0.9",
      cinematic: "curves=vintage,eq=contrast=1.15:brightness=-0.02:saturation=0.85",

      // SOCIAL MEDIA OPTIMIZED (3)
      instagram: "eq=contrast=1.3:brightness=0.08:saturation=1.6:gamma=1.05,unsharp=5:5:1.0:5:5:0.0",
      tiktok: "eq=contrast=1.4:brightness=0.1:saturation=1.5,curves=all='0/0.05 0.5/0.55 1/0.98'",
      youtube: "eq=contrast=1.15:brightness=0.05:saturation=1.1:gamma=1.02",

      // MOOD-BASED PRESETS (3)
      dramatic: "eq=contrast=1.5:brightness=-0.15:saturation=0.8:gamma=0.85,curves=all='0/0 0.3/0.15 0.7/0.7 1/0.95'",
      pastel: "eq=contrast=0.9:brightness=0.12:saturation=0.65:gamma=1.15,curves=all='0/0.1 0.5/0.55 1/0.98'",
      neon: "eq=contrast=1.4:brightness=0.05:saturation=1.8:gamma=0.95,hue=s=1.3,curves=r='0/0.1 0.5/0.6 1/0.98':g='0/0.05 0.5/0.55 1/0.92':b='0/0.15 0.5/0.65 1/1'",

      // FILM EMULATIONS (5)
      vintage: "curves=vintage,eq=contrast=0.95:brightness=0.08:saturation=0.7:gamma=1.1",
      noir: "eq=contrast=1.5:brightness=0.02:saturation=0,curves=all='0/0.1 0.3/0.25 0.7/0.75 1/0.95'",
      golden: "eq=contrast=1.15:brightness=0.05:saturation=1.2,curves=r='0/0.1 0.5/0.6 1/0.98':g='0/0.05 0.5/0.55 1/0.92':b='0/0 0.5/0.4 1/0.8'",
      sunset: "eq=contrast=1.25:brightness=0.03:saturation=1.3,curves=r='0/0.15 0.5/0.65 1/1':g='0/0.08 0.5/0.5 1/0.9':b='0/0.1 0.5/0.55 1/0.95'",
      highcontrast: "eq=contrast=1.4:brightness=0:saturation=1.15,curves=all='0/0.05 0.5/0.5 1/0.95'",

      // No grading
      none: "",
    };

    const filter = filters[mood] || filters.corporate;

    // If no filter selected, just copy the file
    if (filter === "") {
      return videoPath;
    }

    return new Promise((resolve, reject) => {
      ffmpeg(videoPath)
        .videoFilters(filter)
        .output(outputPath)
        .videoCodec("libx264")
        .audioCodec("copy")
        .outputOptions([
          '-preset', 'ultrafast',
          '-threads', '0',  // PERFORMANCE: Fast encoding without quality loss
          '-crf', '20'
        ])
        .on("end", () => {
          const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
          console.log(`[applyColorGrading] Filter applied in ${elapsed}s`);
          resolve(outputPath);
        })
        .on("error", reject)
        .run();
    });
  }

  static async createTransition(
    clip1Path: string,
    clip2Path: string,
    transitionType: "cut" | "fade" | "dissolve" | "zoom" = "cut",
    engagementScore?: number // NEW: Use engagement to determine transition intensity
  ): Promise<string> {
    const outputId = nanoid();
    const outputPath = path.join(VIDEOS_DIR, `transition-${outputId}.mp4`);

    if (transitionType === "cut") {
      // Simple concatenation for jump cuts
      await this.concatenateClips([clip1Path, clip2Path], outputPath);
      return outputPath;
    }

    // Use ZOOM transition for high engagement clips (>85 score)
    if (transitionType === "zoom" || (engagementScore && engagementScore > 85)) {
      return new Promise((resolve, reject) => {
        ffmpeg()
          .input(clip1Path)
          .input(clip2Path)
          .complexFilter([
            // Zoom out from clip1 while fading
            `[0:v]scale=iw*1.2:ih*1.2,fade=out:st=0:d=0.3[v0]`,
            // Zoom in to clip2 while fading
            `[1:v]scale=iw*0.8:ih*0.8,fade=in:st=0:d=0.3,scale=iw/0.8:ih/0.8[v1]`,
            // Overlay with crossfade
            `[v0][v1]xfade=transition=fade:duration=0.3:offset=0[v]`,
            `[0:a][1:a]acrossfade=d=0.3[a]`,
          ])
          .map("[v]")
          .map("[a]")
          .output(outputPath)
          .on("end", () => resolve(outputPath))
          .on("error", reject)
          .run();
      });
    }

    return new Promise((resolve, reject) => {
      // For fade/dissolve transitions
      const transitionDuration = transitionType === "fade" ? 0.5 : 1;

      ffmpeg()
        .input(clip1Path)
        .input(clip2Path)
        .complexFilter([
          `[0:v][1:v]xfade=transition=fade:duration=${transitionDuration}:offset=0[v]`,
          `[0:a][1:a]acrossfade=d=${transitionDuration}[a]`,
        ])
        .map("[v]")
        .map("[a]")
        .output(outputPath)
        .on("end", () => resolve(outputPath))
        .on("error", reject)
        .run();
    });
  }

  static getPublicPath(fullPath: string): string {
    // Convert full filesystem path to public URL path
    // All files are now in uploads/ (persistent storage)
    const uploadsIndex = fullPath.indexOf("/uploads/");
    if (uploadsIndex >= 0) {
      return fullPath.substring(uploadsIndex);
    }
    // Fallback for legacy paths
    return fullPath.replace(process.cwd(), "");
  }

  static getFullPath(publicPath: string): string {
    // Convert public URL path to full filesystem path
    // Both /processing and /uploads now point to same location (uploads/)
    if (publicPath.startsWith("/processing/") || publicPath.startsWith("/uploads/")) {
      // Strip leading slash so path.join works correctly
      return path.join(process.cwd(), publicPath.replace(/^\/+/, "").replace("processing/", "uploads/"));
    }
    return publicPath;
  }


  // Add subtitles to video from transcription
  // Helper to convert hex color to ASS format (&HAABBGGRR&)
  private static hexToAssColor(hexColor: string, opacity: number = 100): string {
    // Remove # if present
    const hex = hexColor.replace('#', '');
    // Extract RGB components
    const r = hex.substring(0, 2);
    const g = hex.substring(2, 4);
    const b = hex.substring(4, 6);
    // Calculate alpha (0-255, where 0 is opaque, 255 is transparent)
    const alpha = Math.round((100 - opacity) * 255 / 100);
    const alphaHex = alpha.toString(16).padStart(2, '0');
    // ASS format is &HAABBGGRR& (alpha, blue, green, red - reverse of RGB!)
    return `&H${alphaHex}${b}${g}${r}&`.toUpperCase();
  }

  // Detect emphasis keywords for kinetic typography with enhanced detection + INTENSITY PRESETS
  private static detectEmphasisWords(
    text: string,
    kineticIntensity: "subtle" | "normal" | "extreme" = "normal"
  ): Array<{ word: string; intensity: number }> {
    // KINETIC INTENSITY MODIFIERS
    const intensityMultipliers = {
      subtle: 0.5,   // 110% max (gentle)
      normal: 1.0,   // 150% max (balanced)
      extreme: 1.5,  // 200% max (explosive)
    };

    const multiplier = intensityMultipliers[kineticIntensity];

    // High-intensity keywords
    const highIntensityKeywords = [
      'wow', 'amazing', 'incredible', 'insane', 'crazy', 'shocking',
      'huge', 'massive', 'epic', 'legendary', 'unbelievable'
    ];

    // Medium-intensity keywords
    const mediumIntensityKeywords = [
      'perfect', 'best', 'awesome', 'fantastic', 'excellent',
      'never', 'always', 'everything', 'everyone', 'beautiful'
    ];

    // Low-intensity keywords
    const lowIntensityKeywords = [
      'great', 'good', 'secret', 'truth', 'important', 'key',
      'critical', 'essential', 'powerful', 'strong'
    ];

    const words = text.toLowerCase().split(/\s+/);
    const emphasisWords: Array<{ word: string; intensity: number }> = [];

    for (const word of words) {
      const cleanWord = word.replace(/[.,!?]/g, '');

      if (highIntensityKeywords.includes(cleanWord)) {
        const baseIntensity = 150;
        const adjustedIntensity = 100 + ((baseIntensity - 100) * multiplier);
        emphasisWords.push({ word: cleanWord, intensity: adjustedIntensity });
      } else if (mediumIntensityKeywords.includes(cleanWord)) {
        const baseIntensity = 130;
        const adjustedIntensity = 100 + ((baseIntensity - 100) * multiplier);
        emphasisWords.push({ word: cleanWord, intensity: adjustedIntensity });
      } else if (lowIntensityKeywords.includes(cleanWord)) {
        const baseIntensity = 120;
        const adjustedIntensity = 100 + ((baseIntensity - 100) * multiplier);
        emphasisWords.push({ word: cleanWord, intensity: adjustedIntensity });
      }
    }

    console.log(`[Kinetics] Intensity preset: ${kineticIntensity} (${multiplier}x multiplier)`);
    return emphasisWords;
  }

  // Create subtitle file with ADVANCED KINETIC TYPOGRAPHY (per-word animations)
  static writeSubtitlesFile(
    segments: Array<{ start: number; end: number; text: string }>,
    config: {
      fontSize: number;
      fontColor: string;
      fontName?: string;
      backgroundColor?: string;
      backgroundOpacity?: number;
      position?: "top" | "center" | "bottom";
      videoHeight?: number;
      preset?: "tiktok" | "instagram" | "youtube" | "professional" | "custom" | "alex-hormozi" | "mr-beast" | "karaoke" | "minimal" | "bold-impact" | "neon-glow";
      language?: string;
      kineticIntensity?: "subtle" | "normal" | "extreme";
      kineticType?: "bounce" | "scale" | "wave" | "pop" | "spring" | "karaoke"; // NEW: Animation types
      outlineWidth?: number;
      shadowStrength?: number;
      enableKinetics?: boolean;
    }
  ): { srtPath: string; assStyle: string; cleanup: () => void } {
    const srtId = nanoid();
    const srtPath = path.join(VIDEOS_DIR, `subtitles-${srtId}.srt`);

    // Generate SRT content with ADVANCED PER-WORD KINETICS
    let srtContent = "";
    segments.forEach((segment, index) => {
      srtContent += `${index + 1}\n`;
      srtContent += `${this.formatSrtTime(segment.start)} --> ${this.formatSrtTime(segment.end)}\n`;

      // Add kinetic effects if enabled
      if (config.enableKinetics) {
        const kineticIntensity = config.kineticIntensity || "normal";
        const kineticType = config.kineticType || "bounce";
        const emphasisWords = this.detectEmphasisWords(segment.text, kineticIntensity);
        let styledText = segment.text;

        // ALEX HORMOZI PRESET: Force uppercase + red/yellow highlights
        if (config.preset === "alex-hormozi") {
          styledText = styledText.toUpperCase();
        }

        // MR. BEAST PRESET: Add yellow box background
        if (config.preset === "mr-beast") {
          // Yellow box with black text (reversed from normal)
          styledText = `{\\3c&H00FFFF&\\4c&H000000&\\bord8}${styledText}{\\r}`;
        }

        // KARAOKE MODE: Highlight each word sequentially
        if (config.preset === "karaoke" || kineticType === "karaoke") {
          const words = styledText.split(/\s+/);
          const wordDuration = (segment.end - segment.start) / words.length;
          let karaokeText = "";

          words.forEach((word, wordIndex) => {
            const wordStart = segment.start + (wordIndex * wordDuration);
            const wordEnd = wordStart + wordDuration;
            // Color transition from white to yellow as word is spoken
            karaokeText += `{\\k${Math.floor(wordDuration * 100)}}${word} `;
          });

          styledText = karaokeText.trim();
        } else {
          // Apply per-word animations based on type
          emphasisWords.forEach(({ word, intensity }) => {
            const regex = new RegExp(`\\b${word}\\b`, 'gi');

            let animation = '';
            switch (kineticType) {
              case "bounce":
                // Bounce: up -> down -> settle with spring physics
                animation = `{\\move(0,0,0,-10,0,50)\\t(50,100,\\move(0,-10,0,5))\\t(100,150,\\move(0,5,0,0))}`;
                break;

              case "scale":
                // Scale with overshoot (spring physics)
                const scaleIn = `{\\t(0,50,\\fscx${intensity * 1.1}\\fscy${intensity * 1.1})}`;
                const scaleBack = `{\\t(50,100,\\fscx${intensity}\\fscy${intensity})}`;
                const scaleOut = `{\\t(100,150,\\fscx100\\fscy100)}`;
                animation = scaleIn + scaleBack + scaleOut;
                break;

              case "wave":
                // Wave: rotate slightly while scaling
                animation = `{\\t(0,100,\\fscx${intensity}\\fscy${intensity}\\frz-5)\\t(100,200,\\fscx100\\fscy100\\frz0)}`;
                break;

              case "pop":
                // Pop: instant scale then bounce out
                animation = `{\\fscx${intensity}\\fscy${intensity}\\t(0,150,\\fscx100\\fscy100)}`;
                break;

              case "spring":
                // Spring: overshoot -> undershoot -> settle (realistic physics)
                animation = `{\\t(0,33,\\fscx${intensity * 1.2}\\fscy${intensity * 1.2})}` +
                           `{\\t(33,66,\\fscx${intensity * 0.95}\\fscy${intensity * 0.95})}` +
                           `{\\t(66,100,\\fscx${intensity}\\fscy${intensity})}` +
                           `{\\t(100,150,\\fscx100\\fscy100)}`;
                break;

              default: // bounce
                animation = `{\\t(0,100,\\fscx${intensity}\\fscy${intensity})}` +
                           `{\\t(100,200,\\fscx100\\fscy100)}`;
            }

            // Add color flash for MR. BEAST / ALEX HORMOZI presets
            let colorFlash = '';
            if (config.preset === "mr-beast") {
              colorFlash = `{\\c&HFF0000&}`; // Red flash
            } else if (config.preset === "alex-hormozi") {
              colorFlash = `{\\c&H00FFFF&}`; // Yellow flash
            }

            styledText = styledText.replace(regex, `${animation}${colorFlash}$&{\\r}`);
          });
        }

        srtContent += `${styledText}\n\n`;
      } else {
        srtContent += `${segment.text}\n\n`;
      }
    });

    fs.writeFileSync(srtPath, srtContent);

    // V2 QUALITY: Professional preset-based styling + CELEBRITY PRESETS
    const preset = config.preset || "tiktok";
    const presetConfigs = {
      tiktok: {
        outline: 4,
        shadow: 2,
        bold: 1,
        fontName: "Arial Black",
        bgColor: "#000000", // Black background
        primaryColor: "#FFFFFF", // White text
      },
      instagram: {
        outline: 3,
        shadow: 1.5,
        bold: 1,
        fontName: "Helvetica",
        bgColor: "#000000",
        primaryColor: "#FFFFFF",
      },
      youtube: {
        outline: 2,
        shadow: 1,
        bold: 0,
        fontName: "Roboto",
        bgColor: "#000000",
        primaryColor: "#FFFFFF",
      },
      professional: {
        outline: 1,
        shadow: 0.5,
        bold: 0,
        fontName: "Arial",
        bgColor: "#000000",
        primaryColor: "#FFFFFF",
      },
      // CELEBRITY PRESETS
      "alex-hormozi": {
        outline: 5,
        shadow: 3,
        bold: 1,
        fontName: "Arial Black",
        bgColor: "#000000", // Black BG
        primaryColor: "#FFFF00", // Yellow text
      },
      "mr-beast": {
        outline: 8, // MAXIMUM outline
        shadow: 5,
        bold: 1,
        fontName: "Impact",
        bgColor: "#FFFF00", // YELLOW BACKGROUND (signature MrBeast style)
        primaryColor: "#000000", // BLACK TEXT on yellow
      },
      // NEW ADVANCED PRESETS
      "karaoke": {
        outline: 3,
        shadow: 1,
        bold: 1,
        fontName: "Arial Black",
        bgColor: "#000000",
        primaryColor: "#FFFFFF",
        // Special: Word-by-word highlight animation (handled in kinetics)
      },
      "minimal": {
        outline: 1,
        shadow: 0,
        bold: 0,
        fontName: "Helvetica Neue",
        bgColor: "#000000",
        primaryColor: "#FFFFFF",
        // Clean, understated look
      },
      "bold-impact": {
        outline: 8, // MAXIMUM visibility
        shadow: 5,
        bold: 1,
        fontName: "Impact",
        bgColor: "#000000",
        primaryColor: "#FFFFFF",
        // Giant readable text for accessibility
      },
      "neon-glow": {
        outline: 2,
        shadow: 8, // Strong glow effect via shadow
        bold: 1,
        fontName: "Arial Black",
        bgColor: "#000000",
        primaryColor: "#FF00FF", // Magenta for neon effect
        // Neon glow simulated with large shadow
      },
      custom: {
        outline: config.outlineWidth || 2,
        shadow: config.shadowStrength || 1,
        bold: 0,
        fontName: "Arial",
        bgColor: "#000000",
        primaryColor: "#FFFFFF",
      }
    };

    const presetStyleConfig = presetConfigs[preset as keyof typeof presetConfigs];

    // MULTI-LANGUAGE FONT FALLBACKS
    const languageFonts: Record<string, string> = {
      zh: "Noto Sans SC", // Simplified Chinese
      "zh-TW": "Noto Sans TC", // Traditional Chinese
      ar: "Noto Naskh Arabic", // Arabic
      ru: "Noto Sans", // Russian
      ja: "Noto Sans JP", // Japanese
      ko: "Noto Sans KR", // Korean
    };

    // Override font if language specified
    if (config.language && languageFonts[config.language]) {
      presetStyleConfig.fontName = languageFonts[config.language];
      console.log(`[Subtitles] Using ${languageFonts[config.language]} font for language: ${config.language}`);
    }

    // Override with manual font if specified
    if (config.fontName) {
      presetStyleConfig.fontName = config.fontName;
    }

    // DYNAMIC FONT SIZING: Calculate optimal size based on video height
    // Industry standard: 5-7% of video height for mobile readability
    let optimalFontSize = config.fontSize;
    if (config.videoHeight) {
      // Use 5.5% of video height as optimal size
      optimalFontSize = Math.floor(config.videoHeight * 0.055);
      console.log(`[writeSubtitlesFile] Dynamic font sizing: ${config.videoHeight}px height → ${optimalFontSize}px font (5.5%)`);
    } else {
      console.log(`[writeSubtitlesFile] Using manual font size: ${config.fontSize}px (no video height provided)`);
    }

    // Generate ASS style with PROFESSIONAL formatting + PRESET COLORS
    const presetPrimaryColor = presetStyleConfig.primaryColor || config.fontColor;
    const presetBgColor = presetStyleConfig.bgColor || config.backgroundColor || "#000000";

    const primaryColor = this.hexToAssColor(presetPrimaryColor, 100);
    const outlineColor = this.hexToAssColor("#000000", 100); // Black outline for max contrast
    const shadowColor = this.hexToAssColor("#000000", 70); // Semi-transparent shadow
    const bgColor = this.hexToAssColor(presetBgColor, config.backgroundOpacity || 85);

    // Alignment: 1-3 bottom, 4-6 middle, 7-9 top (center horizontally)
    const alignment = config.position === "bottom" ? 2 : config.position === "top" ? 8 : 5;
    const marginV = config.position === "bottom" ? 30 : config.position === "top" ? 30 : 0; // More margin for readability

    // PROFESSIONAL ASS STYLING - TikTok/Instagram quality with dynamic font sizing
    const assStyle = `FontName=${presetStyleConfig.fontName},FontSize=${optimalFontSize},PrimaryColour=${primaryColor},OutlineColour=${outlineColor},BackColour=${shadowColor},BorderStyle=1,Outline=${presetStyleConfig.outline},Shadow=${presetStyleConfig.shadow},Bold=${presetStyleConfig.bold},Alignment=${alignment},MarginV=${marginV},MarginL=20,MarginR=20`;

    return {
      srtPath,
      assStyle,
      cleanup: () => {
        try {
          if (fs.existsSync(srtPath)) {
            fs.unlinkSync(srtPath);
          }
        } catch (err) {
          console.error(`Failed to cleanup subtitle file ${srtPath}:`, err);
        }
      }
    };
  }

  static async addSubtitles(
    videoPath: string,
    transcription: string,
    style: "modern" | "classic" | "minimal" = "modern",
    position: "bottom" | "top" | "center" = "bottom"
  ): Promise<string> {
    const outputId = nanoid();
    const outputPath = path.join(VIDEOS_DIR, `subtitled-${outputId}.mp4`);
    const srtPath = path.join(VIDEOS_DIR, `subtitles-${outputId}.srt`);

    // Generate SRT file from transcription (simple word-based timing)
    const words = transcription.split(" ");
    const wordsPerSubtitle = 5;
    const durationPerSubtitle = 2; // seconds

    let srtContent = "";
    for (let i = 0; i < words.length; i += wordsPerSubtitle) {
      const index = Math.floor(i / wordsPerSubtitle) + 1;
      const startTime = (i / wordsPerSubtitle) * durationPerSubtitle;
      const endTime = startTime + durationPerSubtitle;
      const text = words.slice(i, i + wordsPerSubtitle).join(" ");

      srtContent += `${index}\n`;
      srtContent += `${this.formatSrtTime(startTime)} --> ${this.formatSrtTime(endTime)}\n`;
      srtContent += `${text}\n\n`;
    }

    fs.writeFileSync(srtPath, srtContent);

    // Subtitle styles
    const styles: Record<string, string> = {
      modern: "FontName=Arial,FontSize=24,PrimaryColour=&H00FFFFFF,OutlineColour=&H00000000,BackColour=&H80000000,Bold=1,Outline=2,Shadow=1",
      classic: "FontName=Times New Roman,FontSize=22,PrimaryColour=&H00FFFFFF,OutlineColour=&H00000000,Bold=0,Outline=1",
      minimal: "FontName=Helvetica,FontSize=20,PrimaryColour=&H00FFFFFF,BackColour=&H00000000,Bold=0,Outline=0",
    };

    const alignment = position === "bottom" ? 2 : position === "top" ? 8 : 5;
    const marginV = position === "bottom" ? 20 : position === "top" ? 20 : 0;

    return new Promise((resolve, reject) => {
      ffmpeg(videoPath)
        .outputOptions([
          `-vf subtitles=${srtPath}:force_style='${styles[style]},Alignment=${alignment},MarginV=${marginV}'`,
          '-preset', 'ultrafast',
          '-threads', '0',
          '-crf', '20'
        ])
        .output(outputPath)
        .on("end", () => {
          fs.unlinkSync(srtPath); // Clean up SRT file
          resolve(outputPath);
        })
        .on("error", reject)
        .run();
    });
  }

  // Helper to format time for SRT files
  private static formatSrtTime(seconds: number): string {
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const secs = Math.floor(seconds % 60);
    const ms = Math.floor((seconds % 1) * 1000);

    return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(secs).padStart(2, '0')},${String(ms).padStart(3, '0')}`;
  }

  // Add title card to video
  static async addTitleCard(
    videoPath: string,
    titleText: string,
    duration: number = 3
  ): Promise<string> {
    const outputId = nanoid();
    const titleCardPath = path.join(VIDEOS_DIR, `title-${outputId}.mp4`);
    const outputPath = path.join(VIDEOS_DIR, `titled-${outputId}.mp4`);

    // Create title card video
    return new Promise((resolve, reject) => {
      ffmpeg()
        .input(`color=c=black:s=1920x1080:d=${duration}`)
        .inputFormat('lavfi')
        .outputOptions([
          `-vf drawtext=text='${titleText.replace(/'/g, "\\'")}':fontcolor=white:fontsize=60:box=1:boxcolor=black@0.5:boxborderw=5:x=(w-text_w)/2:y=(h-text_h)/2`,
          '-preset', 'ultrafast',
          '-threads', '0',
          '-crf', '20'
        ])
        .output(titleCardPath)
        .on("end", () => {
          // Concatenate title card with video
          this.concatenateClips([titleCardPath, videoPath], outputPath)
            .then(() => {
              fs.unlinkSync(titleCardPath); // Clean up title card
              resolve(outputPath);
            })
            .catch(reject);
        })
        .on("error", reject)
        .run();
    });
  }

  // Add end card to video
  static async addEndCard(
    videoPath: string,
    endCardText: string,
    duration: number = 3
  ): Promise<string> {
    const outputId = nanoid();
    const endCardPath = path.join(VIDEOS_DIR, `endcard-${outputId}.mp4`);
    const outputPath = path.join(VIDEOS_DIR, `ended-${outputId}.mp4`);

    // Create end card video
    return new Promise((resolve, reject) => {
      ffmpeg()
        .input(`color=c=black:s=1920x1080:d=${duration}`)
        .inputFormat('lavfi')
        .outputOptions([
          `-vf drawtext=text='${endCardText.replace(/'/g, "\\'")}':fontcolor=white:fontsize=40:box=1:boxcolor=black@0.5:boxborderw=5:x=(w-text_w)/2:y=(h-text_h)/2`,
          '-preset', 'ultrafast',
          '-threads', '0',
          '-crf', '20'
        ])
        .output(endCardPath)
        .on("end", () => {
          // Concatenate video with end card
          this.concatenateClips([videoPath, endCardPath], outputPath)
            .then(() => {
              fs.unlinkSync(endCardPath); // Clean up end card
              resolve(outputPath);
            })
            .catch(reject);
        })
        .on("error", reject)
        .run();
    });
  }


  static async regenerateVideoFromClips(
    sourceVideoPath: string,
    slices: Array<{ id: string; startTime: number; endTime: number }>,
    clipSequence: string[],
    videoType: "short" | "standard" | "comprehensive",
    aspectRatio?: "9:16" | "1:1" | "16:9",
    refinedParams?: {
      transitionStyle?: string;
      pacing?: "slow" | "normal" | "fast";
      colorGrade?: string;
      enableJLCuts?: boolean;
      jlCutType?: "j-cut" | "l-cut" | "auto";
    }
  ): Promise<string> {
    console.log(`[regenerate] Creating ${videoType} video from ${clipSequence.length} clips (PARALLEL MODE)`);
    if (refinedParams) {
      console.log(`[regenerate] Using refined params:`, refinedParams);
    }

    const tempClipPaths: string[] = [];

    try {
      // PARALLEL PROCESSING: Extract all clips concurrently
      const clipSpecs = clipSequence
        .map(sliceId => {
          const slice = slices.find(s => s.id === sliceId);
          if (!slice) {
            console.warn(`[regenerate] Slice ${sliceId} not found, skipping`);
            return null;
          }
          return {
            startTime: slice.startTime,
            endTime: slice.endTime,
            id: sliceId
          };
        })
        .filter(spec => spec !== null) as Array<{ startTime: number; endTime: number; id: string }>;

      if (clipSpecs.length === 0) {
        throw new Error("No valid clips to extract");
      }

      // Extract all clips in parallel (3-5x faster than sequential)
      const extractedClips = await this.extractClipsParallel(
        sourceVideoPath,
        clipSpecs,
        { reEncode: false } // Use stream copy for speed
      );

      tempClipPaths.push(...extractedClips);

      // Create the final concatenated video
      const outputId = nanoid();
      const outputPath = path.join(VIDEOS_DIR, `${videoType}-${outputId}.mp4`);

      console.log(`[regenerate] Concatenating ${tempClipPaths.length} clips into ${outputPath}`);
      await this.concatenateClips(tempClipPaths, outputPath);

      // Apply aspect ratio cropping if specified
      let finalPath = outputPath;
      if (aspectRatio && aspectRatio !== "16:9") {
        console.log(`[regenerate] Applying aspect ratio: ${aspectRatio}`);
        finalPath = await this.cropToAspectRatio(outputPath, aspectRatio);
        // Clean up uncropped temp file
        try {
          fs.unlinkSync(outputPath);
        } catch (err) {
          console.warn(`[regenerate] Failed to delete uncropped temp file`);
        }
      }

      // Clean up temp clips
      for (const tempPath of tempClipPaths) {
        try {
          fs.unlinkSync(tempPath);
        } catch (err) {
          console.warn(`[regenerate] Failed to delete temp clip ${tempPath}:`, err);
        }
      }

      // Apply refined parameters if provided
      if (refinedParams) {
        // Apply color grading if specified
        if (refinedParams.colorGrade && refinedParams.colorGrade !== 'none') {
          console.log(`[regenerate] Applying refined color grade: ${refinedParams.colorGrade}`);
          const gradedPath = await this.applyColorGrading(finalPath, refinedParams.colorGrade);
          // Clean up non-graded version
          if (finalPath !== gradedPath) {
            try {
              fs.unlinkSync(finalPath);
            } catch (err) {
              console.warn(`[regenerate] Failed to delete non-graded temp file`);
            }
            finalPath = gradedPath;
          }
        }
      }

      console.log(`[regenerate] Video regenerated successfully: ${finalPath}`);
      return finalPath;
    } catch (error) {
      // Clean up temp clips on error
      for (const tempPath of tempClipPaths) {
        try {
          fs.unlinkSync(tempPath);
        } catch (err) {
          // Ignore cleanup errors
        }
      }
      throw error;
    }
  }

  static async exportWithFormatAndQuality(
    videoPath: string,
    format: string,
    quality: string
  ): Promise<string> {
    const outputId = nanoid();
    const fileExtension = format === "mov" ? "mov" : format === "webm" ? "webm" : "mp4";
    const outputPath = path.join(VIDEOS_DIR, `export-${outputId}.${fileExtension}`);

    const qualitySettings: Record<string, { width: number; height: number; bitrate: string }> = {
      high: { width: 1920, height: 1080, bitrate: "5000k" },
      medium: { width: 1280, height: 720, bitrate: "2500k" },
      low: { width: 854, height: 480, bitrate: "1000k" },
    };

    const settings = qualitySettings[quality] || qualitySettings.high;

    return new Promise((resolve, reject) => {
      const command = ffmpeg(videoPath)
        .size(`${settings.width}x${settings.height}`)
        .videoBitrate(settings.bitrate)
        .output(outputPath);

      if (format === "mp4") {
        command
          .videoCodec("libx264")
          .audioCodec("aac")
          .outputOptions([
            "-preset", "ultrafast",
            "-threads", "0",
            "-crf", "23",
            "-pix_fmt", "yuv420p"
          ]);
      } else if (format === "webm") {
        command
          .videoCodec("libvpx-vp9")
          .audioCodec("libopus")
          .outputOptions([
            "-deadline", "good",
            "-cpu-used", "2",
            "-row-mt", "1"
          ]);
      } else if (format === "mov") {
        command
          .videoCodec("prores_ks")
          .audioCodec("pcm_s16le")
          .outputOptions([
            "-profile:v", "2",
            "-vendor", "apl0",
            "-bits_per_mb", "8000",
            "-pix_fmt", "yuv422p10le"
          ]);
      }

      command
        .on("end", () => {
          console.log(`[export] Exported video: ${format} (${quality}) -> ${outputPath}`);
          resolve(outputPath);
        })
        .on("error", (err) => {
          console.error(`[export] Export failed:`, err);
          reject(err);
        })
        .run();
    });
  }
}